### ISSUE TITLE
the order in which tests are run is not documented

### ISSUE THREAD

**Issue by drj11** [tlevine/urchin#17]
urchin should document in what order tests are run. Or document that the order is not to be relied upon.

**Comment by tlevine** [comment]
And while we're at it, maybe it's worth considering what

It looks like the tests are ordered like this.

    for test in *
      do_stuff_with_test_file $test
    done

Is it helpful to you if we just say that it gets ordered however `*`
orders things? I don't actually know what that order is. (Do you?)

We could also add a flag to explicitly sort them or something.

**Comment by drj11** [comment]
Yes, i like saying that they're ordered however `*` is ordered. Which is ASCIIbetical (but that seems to be an obscure fact).
